apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: bars.samplecontrollee.k8s.io
spec:
  group: samplecontrollee.k8s.io
  version: v1alpha1
  names:
    kind: Bar
    plural: bars
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            replicas:
              type: integer
              minimum: 1
              maximum: 10
